name: Build Android Apk

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
env:
FORCE_JAVASCRIPT_ACTIONS_TO_NODE24:true
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: npm install-force

    # গুগল ম্যাপস এপিআই কী সেটআপ (যদি আপনি এটি গোপন রাখতে চান)
    - name: Create local.properties
      run: echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" > local.properties

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Buid apk Run on android
      uses: actions/upload-artifact@v4
      with:
        name: RideFuel-Tracker-Debug-APK
        path: app/build/outputs/apk/debug/app-debug.apk
